# Information
site_name: frozenkp's Blog

# Repository
repo_name: 'frozenkp/frozenkp'
repo_url: 'https://github.com/frozenkp/frozenkp.github.io'

# Content
pages:
    - HOME: index.md
    - Writeups:
      - 2014:
        - NoConName qual:
          - inBINcible: Writeups/2014/NoConName_qual/inBINcible.md
      - 2015:
        - B-Sides Vancouver: 
          - Delphi: Writeups/2015/B-Sides_Vancouver/Delphi.md
      - 2017:
        - HITB CTF:
          - 2017, Dating in Singapore: Writeups/2017/HITB_CTF/2017_Dating_in_Singapore.md
          - Flying_High: Writeups/2017/HITB_CTF/Flying_High.md
          - Pasty: Writeups/2017/HITB_CTF/Pasty.md
        - seccon CTF:
          - Qubic Rube: Writeups/2017/seccon_CTF/Qubic_Rube.md
          - putchar music: Writeups/2017/seccon_CTF/putchar_music.md
      - 2018:
        - BambooFox CTF:
          - water-impossible: Writeups/2018/BambooFox_CTF/water-impossible.md
          - infant-gotoheaven: Writeups/2018/BambooFox_CTF/infant-gotoheaven.md
          - infant-gogogo: Writeups/2018/BambooFox_CTF/infant-gogogo.md
      - Others:
        - pwnable.tw:
          - Start: Writeups/Others/pwnable.tw/Start.md
          - hacknote: Writeups/Others/pwnable.tw/hacknote.md 
          - dubblesort: Writeups/Others/pwnable.tw/dubblesort.md 
          - criticalheap: Writeups/Others/pwnable.tw/criticalheap.md 

# Theme
theme: 'material'

# Customization
extra_javascript: 
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Extensions
markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tilde
